name: hoqoqi
description: "تطبيق مؤسسة حقوق الإنسان - طلب التعويضات من دولة الكويت"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  firebase_analytics: ^10.10.5
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.0
  
  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  
  # File Handling
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  
  # Form Validation
  email_validator: ^2.1.17
  
  # Date & Time
  intl: ^0.19.0
  
  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Utils
  path_provider: ^2.1.2
  
  # Icons
  cupertino_icons: ^1.0.6
  
  # File Handling
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  path_provider: ^2.1.3
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Network
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.5
  
  # Validation
  form_validator: ^2.1.1
  
  # Date & Time
  intl: ^0.19.0
  
  # Image Processing
  image: ^4.1.7
  flutter_image_compress: ^2.2.0
  
  # Utils
  uuid: ^4.4.0
  path: ^1.9.0
  
  # PDF Generation
  pdf: ^3.10.8
  printing: ^5.12.0
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
